---
- name: Setup GitLab
  hosts: gitlab
    
  tasks:
  - name: Install python-pip
    apt:
      name: python-pip
      update_cache: true
    become: true 

  - name: Install docker-py
    pip:
      name: docker-py>=1.8.0
    become: true 

  - name: Create directories
    file:
      path: '/srv/gitlab/{{ item }}'
      state: directory
      owner: ubuntu
      mode: '0755'
      recurse: yes
    become: true   
    loop:
      - config
      - data
      - logs
  
  - name: Run gitlab container
    docker_container:
      name: gitlab-ansible
      image: 'gitlab/gitlab-ce:latest'
      restart: true
      hostname: 'gitlab.example.com'
      state: started
      env:
        GITLAB_OMNIBUS_CONFIG: external_url 'http://{{ gitlab_host }}'
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
      volumes:
        - '/srv/gitlab/config:/etc/gitlab'
        - '/srv/gitlab/logs:/var/log/gitlab'
        - '/srv/gitlab/data:/var/opt/gitlab'
    become: true    
  
  - name: Show info
    debug:
      msg: "external_url http://{{ gitlab_host }}"  