FROM grafana/grafana:5.0.4

ADD provisioning/dashboards /etc/grafana/provisioning/dashboards
ADD provisioning/datasources /etc/grafana/provisioning/datasources
ADD dashboards /var/lib/grafana/dashboards