{
 "title": "TLEGRAF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "docker_container_net_rx_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_net_rx_bytes" }
   ]
  },
  {
   "title": "docker_container_status_uptime_ns",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_status_uptime_ns[5m])"
    }
   ]
  },
  {
   "title": "docker_container_mem_usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_mem_usage" }
   ]
  },
  {
   "title": "docker_container_cpu_usage_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_total[5m])"
    }
   ]
  }
 ]
}