version: '3.3'
services:
  ui:
    volumes:
      - ./src/ui:/app
    entrypoint: puma --debug -w 2
  post:
    volumes:
      - ./src/post-py:/app
  comment:
    volumes:ss
      - ./src/comment:/app
    entrypoint: puma --debug -w 2
