version: '3.3'
services:
  
  post_db:
    image: mongo:${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    #build: ../src/ui
    image: ${USERNAME}/ui:logging
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net
  
  post:
    #build: ../src/post-py:
    image: ${USERNAME}/post:logging
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net
  
  comment:
    #build: ../src/comment
    image: ${USERNAME}/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.2.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.2.1.0/24"     
