version: '3.3'
services:
  
  post_db:
    image: mongo:${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    #build: ../src/ui
    image: ${USERNAME}/ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  
  post:
    build: ../src/post-py
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
  
  comment:
    #build: ../src/comment
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net
  
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net
      - front_net      

  mongodb-exporter:
    #from https://github.com/percona/mongodb_exporter
    image: ${USERNAME}/mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://post_db:27017
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.2.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.2.1.0/24"
