version: '3.3'
services:
  
  post_db:
    image: mongo:${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  
  ui:
    #build: ../src/ui
    image: ${USERNAME}/ui
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  
  post:
    #build: ../src/post-py:
    image: ${USERNAME}/post
    networks:
      - back_net
      - front_net
  
  comment:
    #build: ../src/comment
    image: ${USERNAME}/comment
    networks:
      - back_net
      - front_net
  
volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.2.2.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.2.1.0/24"     
