---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-db
  template:
    metadata:
      name: post-db
      labels:
        app: post-db
    spec:
      containers:
      - image: mongo:3.2
        name: post-db
